Loading '191' labeled samples from SemanticKITTI under 'train' split ...
[IOU EVAL] IGNORED CLASS:  tensor(0)
[IOU EVAL] INCLUDE CLASS:  tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])
Traceback (most recent call last):
  File "train_sup_only.py", line 166, in <module>
    main()
  File "train_sup_only.py", line 163, in main
    train(logger, model, datasets, args, cfg, device)
  File "/nvme/konglingdong/models/LaserMix/script/trainer/trainer.py", line 149, in train
    logits = model(scan)
  File "/nvme/konglingdong/anaconda3/envs/lasermix/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nvme/konglingdong/models/LaserMix/model/range/fidnet/network.py", line 14, in forward
    middle_feature_maps=self.backend(x)  # [bs, 1024, H, W]
  File "/nvme/konglingdong/anaconda3/envs/lasermix/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nvme/konglingdong/models/LaserMix/model/range/fidnet/network.py", line 239, in forward
    return self._forward_impl(x)
  File "/nvme/konglingdong/models/LaserMix/model/range/fidnet/network.py", line 222, in _forward_impl
    x = self.bn_2(x)
  File "/nvme/konglingdong/anaconda3/envs/lasermix/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nvme/konglingdong/anaconda3/envs/lasermix/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/nvme/konglingdong/anaconda3/envs/lasermix/lib/python3.8/site-packages/torch/nn/functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
